---
title: "test-JenOchs"
output: html_document
date: '2023-02-08'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
```


```{r}
ui <- fluidPage(
titlePanel("Exploring Great Smoky Mountains National Park Phenology Data"),   
tabsetPanel(
    tabPanel("Overview", fluid = TRUE,
             mainPanel(
               img(src = "SmokyMountainsPic.png"),
               h1("Introduction", style = "font-family:'times'; color:green"),
               h3("Great Smoky Mountain National Park", style = "font-family:'times'"),
               p("Great Smoky Mountain National Park covers over 800 square miles of the southeastern United States, stretching along the North Carolina-Tennessee border. The park is one of the most visited in the country, with millions of visitors stopping by to take in the scenery and wildlife. Different times of year bring different sightings as the seasons change, and these changes and observed and documented through the study of phenology.
", style = "font-family:'times'"),
               h3("Phenology", style = "font-family:'times'"),
               p("Phenology is the study of the biological cycles observed in nature, and phenological data for Great Smoky Mountain National Park is displayed in this app. While there is a great number of phenology trends that can be studied, this data explores four:
", style = "font-family:'times'"),
              h6("1. First Leaf Out"),
              h6("2. First Flower"),
              h6("3. 95% Canopy"),
              h6("4. First Fall Leaf Color"),
              p("A great number of factors can influence phenology patterns. Three major factors that are observed and displayed in this app include elevation, precipitation and temperature. These factors and others can cause noticeable shifts in cycles from year to year, so observing phenology trends over lengths of time is necessary to find patterns of change."),
               h1("Tabs", style = "font-family:'times'; color:green"),
               h3("Quick Glance"),
                p("This tab provides a brief look at phenophase observations for one of eleven tree species in a specific year. "),
               h3("Time Series"),
                p("With the time series tab, you not only select a species and phenophase, but also an elevation band as this influences onset of changes. The user can select a range of years to see how the patterns of a particular phenophase changes over time."),
               h3("Bivariate"),
                p("Lastly, the bivariate tab allows the user to visualize the impacts of temperature or precipitation on the phenophase onset for a species over time."),
               h3("Creators", style = "font-family:'times'"),
               p("This app was created as a senior capstone project as a collaboration between the National Park Service and Virginia Tech students (Zhao, Jason, Sean, Jen)", style = "font-family:'times'")
               
             ))
    )
) 

shinyApp(ui = ui, server = server)
```


