---
title: "data_sampling"
author: "sean"
date: "2023-03-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(shinydashboard)
library(markdown)
library(rmarkdown)
library(rnpn)
library(dplyr)
library(lubridate)
library(styler)
library(ggplot2)
library(bslib)
library(thematic)
library(ragg)
library(showtext)
library(tidyverse)
library(rsconnect)

rm(list = ls())
setwd("C:/Users/Sean/Documents/S23-EDS-Phenology_v1/app")
cdf <- read.csv("www/data/cdf.csv")
setwd("C:/Users/Sean/Documents/S23-EDS-Phenology/app")

```

``` {r rnpn_download_example}
# cdf <- npn_download_status_data(
#   request_source = 'VT23 EDS APP DEMO', 
#   network_ids = c(72),
#   years = c(2010:2020), 
#   species_ids = c(3, 98, 61, 82, 1187, 97, 1172, 823, 100, 79, 1189), 
#   additional_fields = c("Site_Name", "Network_Name", "Phenophase_Category"),
#   climate_data = TRUE)
```

# ----------------------------------------------------- #

#Date formats, elevation categories
```{r data}
#THIS SECTION FORMATS THE DATES AND DIVIDES INTO ITS ELEVATION CATEGORIES
cdf = cdf %>%
  dplyr::mutate(
    year = lubridate::year(observation_date),
    month = lubridate::month(observation_date),
    day = lubridate::day(observation_date)
  )
cdf$elev_bands <-
  cut(cdf$elevation_in_meters,
      c(-Inf, 800, 1300, Inf),
      c("<800m", "800-1300m", ">1300m"))

#################################################################################################################################
#################################################################################################################################
#THIS SECTION 
#Creates Intensity Dataset - icdf
#Filter to 95% Intensity and the Leaves phenophase, get correct columns
icdf <- subset(
  cdf,
  intensity_value == '95% or more' &
    phenophase_description == 'Leaves',
  select = c(
    species, species_id, phenophase_id, common_name, phenophase_description,
    intensity_value, site_name, elevation_in_meters, elev_bands, tmin_winter, 
    tmin_spring, tmax_winter, tmax_spring, daylength, individual_id, year, day_of_year
  )
)

#################################################################################################################################
#################################################################################################################################
#Select the earliest DOY of 95% canopy full by year by individual
icdf2 <- icdf %>%
  group_by(year, individual_id, common_name) %>%
  filter(day_of_year == min(day_of_year))

icdf3 <- icdf %>%
  group_by(year, common_name) %>%
  filter(day_of_year == min(day_of_year))

#################################################################################################################################
#################################################################################################################################
#Create Phenophase Status Dataset - cdf
#Filter to 1s (yes to phenophase status), get correct columns
cdf1 <- subset(
  cdf,
  phenophase_status == 1,
  select = c(
    species_id, phenophase_id, common_name,
    phenophase_description, site_name, elevation_in_meters, elev_bands,
    tmin_winter,tmin_spring, tmax_winter, tmax_spring,
    prcp_spring, prcp, acc_prcp,
    daylength, individual_id, year, day_of_year
  )
)

cdfa <- subset(
  cdf,
  phenophase_status == 1 | phenophase_status == 0,
  select = c(
    common_name,phenophase_description,phenophase_status,
    elev_bands,year,day_of_year
  )
)
cdfa$y <- cut(cdfa$phenophase_status, breaks = 2)



#################################################################################################################################
#################################################################################################################################
#Select the earliest DOY by year by individual
cdf2 <- cdf1 %>%
  group_by(year, individual_id, common_name, phenophase_description) %>%
  filter(day_of_year == min(day_of_year))

cdf3 <- cdf1 %>%
  group_by(year, individual_id, common_name) %>%
  filter(day_of_year == min(day_of_year))

####
bivar_weather <- cdf2 %>%
  group_by(year, individual_id, common_name, phenophase_description) %>%
  filter(day_of_year == min(day_of_year),
         phenophase_description == "Leaves")
```

``` {r write_files}
## these are sample files to host on GitHub
write.csv(x = cdfa, file = "cdfa.csv", row.names = FALSE)
write.csv(x = cdf2, file = "cdf2.csv", row.names = FALSE)
write.csv(x = icdf2, file = "icdf2.csv", row.names = FALSE)
write.csv(x = bivar_weather, file = "bivar_weather.csv", row.names = FALSE)
```
